# Generated by Django 2.2.6 on 2019-10-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='cover',
            field=models.ImageField(default='/static/banner_default.png', upload_to='images/banner', verbose_name='轮播图'),
        ),
    ]
